svvimming/fuites-anarchive

packages/be/modules/uploader/websocket/file-upload-chunk.js, packages/fe/modules/uploader/components/upload-input.vue
Fixed bug that was not allowing subsequent uploads without a page refresh
=> fix: uploader allows follow-up selections of uploads

packages/fe/components/thingie.vue
Fix for the thingie position mismatched from cursor position
=> fix: drag n drop bug

packages/fe/modules/pocket/components/pocket.vue, packages/fe/pages/index.vue
Dragging state now correctly toggles when thingie is moved between zones
=> fix: dragging state toggle between zones

packages/be/modules/auth/index.js, packages/be/modules/auth/rest/get-authenticate.js, packages/fe/layouts/spaze.vue, packages/fe/modules/pocket/components/pocket.vue, packages/fe/modules/toaster/components/toast.vue, packages/fe/nuxt.config.js, packages/fe/package-lock.json, packages/fe/package.json, packages/fe/plugins/helpers.js, packages/fe/store/general.js
Very basic token auth! Session **_does not_** persist across page refreshes.
=> feat: implemented very basic token authentication

packages/be/modules/auth/rest/get-authenticate.js, packages/be/modules/thingie/rest/post-delete-thingy.js, packages/fe/layouts/spaze.vue, packages/fe/modules/compost/components/compost-portal.vue, packages/fe/store/collections.js
'post delete thingie' endpoint created to:
- 1. remove thingie from the thingie database
- 2. remove the corresponding file entry from the uploads database
- 3. delete the corresponding file in the uploads folder
- 4. ping the client to remove the thingie from the collections store
=> feat: Delete thingie and upload

packages/fe/pages/portal.vue, packages/fe/store/collections.js
Clear collections store thingies on navigating away from the portal page.
=> feat: clear store thingies on navigate away from page

packages/fe/components/landing-site.vue, packages/fe/components/thingie.vue, packages/fe/data/landing.json
- allow spaces in token submit input
- thingie text edit changed from clicking with command to clicking with option
=> feat: allow spaces in token submit input

packages/fe/components/thingies/editor.vue, packages/fe/components/thingies/thingie.vue, packages/fe/modules/pocket/components/pocket.vue, packages/fe/pages/_id.vue, packages/fe/plugins/helpers.js, packages/fe/store/collections.js
Thingie editor component added. This component is nested inside each thingie. Rotation functionality has been moved from the wheel event handler to left and right arrow keys controlled inside the editor. Z-index 'bring to front' and 'send to back' functions have been added to the editor as well.
=> refactor: thingie editor

packages/be/modules/spaze/model/index.js, packages/be/modules/spaze/rest/post-create-spaze.js, packages/be/modules/thingie/rest/post-create-thingy.js, packages/fe/components/prop-board.vue, packages/fe/components/thingies/editor.vue, packages/fe/components/thingies/thingie.vue, packages/fe/modules/pocket/components/pocket.vue, packages/fe/pages/_id.vue, packages/fe/plugins/helpers.js, packages/fe/store/collections.js
A new spaze is created from a thingie dropped in a spaze that is 'metastable'.
=> feat: post create spaze

packages/be/modules/thingie/rest/post-create-thingy.js, packages/fe/components/thingies/image-thingie.vue, packages/fe/components/thingies/thingie.vue
Toggle clip path button added to image thingies.
=> feat: clip path option

packages/fe/components/thingies/sound-thingie.vue, packages/fe/layouts/spaze.vue
Change sound thingie opacity only when audio enabled
=> fix: change sound thingie opacity only when audio enabled

packages/be/modules/spaze/model/index.js, packages/fe/assets/scss/variables.scss, packages/fe/components/landing-site.vue, packages/fe/components/portal.vue, packages/fe/components/thingies/thingie.vue, packages/fe/layouts/spaze.vue, packages/fe/modules/compost/components/compost-portal.vue, packages/fe/modules/pocket/components/pocket.vue, packages/fe/pages/_id.vue
=> feat: xy bounds on spazes

packages/fe/components/thingies/sound-thingie.vue, packages/fe/data/landing.json
=> chore: update tips

packages/be/package-lock.json
=> chore: updated be package-lock

packages/be/modules/uploader/websocket/file-upload-chunk.js, packages/be/modules/uploader/websocket/file-upload-initialize.js, packages/be/package-lock.json, packages/be/package.json, packages/fe/modules/uploader/components/upload-input.vue, packages/fe/package-lock.json, packages/fe/package.json
color thief dependency and function moved from be to fe upload input
=> refactor: color thief fe

packages/fe/modules/uploader/components/upload-input.vue, packages/fe/package-lock.json, packages/fe/package.json
=> test: replace colorthief with fork

packages/be/modules/uploader/websocket/file-upload-initialize.js, packages/fe/components/landing-site.vue, packages/fe/components/thingies/thingie.vue, packages/fe/data/landing.json, packages/fe/modules/pocket/components/single-file-uploader.vue, packages/fe/modules/uploader/components/upload-input.vue
cleanup and move resize into thingie editor mode
=> feat: v1.1.0 cleanup

packages/fe/pages/_id.vue
_id page includes basic undo functionality
=> feat: _id page includes basic undo functionality

packages/fe/pages/_id.vue
=> feat: cleanup basic undo

packages/be/crons/tunneler/index.js
prevent portals being created to compost and pocket
=> feat: prevent portals being created to compost and pocket

packages/be/modules/utilities/index.js
color selection on sound thingie creation
=> fix: color selection on sound thingie creation

packages/be/crons/goa/index.js, packages/be/crons/kleptobot/index.js, packages/be/crons/rezonator/index.js, packages/be/crons/scavenger/index.js, packages/be/crons/tunneler/index.js, packages/be/liftoff.js, packages/be/package-lock.json, packages/be/package.json, packages/fe/modules/pocket/components/pocket.vue
Migrate from node-cron to pm2 cron execution. Crons will be handled by pm2 now instead of node-cron.
=> feat: cron cleanup

packages/be/modules/utilities/index.js
disable localhost cert on websocket
=> test: disable localhost cert on websocket

packages/fe/components/landing-site.vue, packages/fe/data/landing.json, packages/fe/modules/pocket/components/single-file-uploader.vue
additional file upload support/x-browser support
=> feat: additional file upload support/x-browser support

packages/be/crons/tunneler/index.js
=> test: tunneler log

packages/be/crons/tunneler/index.js
=> chore: remove console logs

packages/be/crons/goa/index.js
=> feat: adjust goa thresholds

packages/be/crons/kleptobot/index.js, packages/fe/modules/pocket/components/pocket.vue
kleptobot migrator manipulates db directly
=> fix: kleptobot migrator manipulates db directly

packages/be/crons/goa/index.js, packages/be/crons/kleptobot/index.js
update preaccelerator thresholds/calculations
=> feat: update preaccelerator thresholds/calculations

packages/be/crons/kleptobot/index.js
Kleptobot won't steal things from spazes that have had activity within one day.
=> feat: kleptobot tweaks

packages/be/crons/kleptobot/index.js, packages/fe/modules/pocket/components/single-file-uploader.vue, packages/fe/modules/uploader/components/upload-input.vue, packages/fe/package-lock.json, packages/fe/package.json
Adding: 
- client side image compression to the file uploader
- file size limit on uploads: 8mb
- remove wav audio support
- kleptobot only steals from inactive spaces
=> feat: image compression/file size restrictions

packages/fe/pages/_id.vue
Remove token authentication for a lull nearby page
=> feat: remove token authentication for a lull nearby page

packages/fe/pages/_id.vue
=> feat: re-add auth to a lull nearby

packages/be/crons/goa/index.js, packages/be/crons/kleptobot/index.js, packages/be/crons/rules.json, packages/be/crons/tunneler/index.js, packages/fe/store/general.js
Rules for Kleptobot, Tunneler and Goa crons.
=> feat: cron rules

packages/fe/store/general.js
replace touchmode variable default
=> fix: replace touchmode variable default

packages/fe/layouts/spaze.vue
close editor on clearing editor thingie
=> fix: close editor on clearing editor thingie

packages/fe/components/auth.vue, packages/fe/components/landing-site.vue, packages/fe/components/prop-board.vue, packages/fe/components/thingies/touch-editor.vue, packages/fe/components/thingies/touch-thingie.vue, packages/fe/components/touchmode-toolbar.vue, packages/fe/data/landing.json, packages/fe/data/thingie-editable-params.json, packages/fe/layouts/spaze.vue, packages/fe/pages/_id.vue, packages/fe/pages/compost.vue, packages/fe/store/collections.js, packages/fe/store/general.js
=> feat: mobile tweaks and fixes

README.md
=> feat: readme file added

packages/be/crons/tunneler/index.js, packages/be/modules/portal/model/index.js, packages/fe/components/portal.vue, packages/fe/pages/_id.vue
One portal per unique destination and dedupe portals on fe.
=> feat: unique portals

packages/be/crons/tunneler/index.js, packages/fe/components/portal.vue
Fix: group portal refs by unique destination and create a unique portal for each set.
=> fix: account for all unique connections

packages/be/modules/thingie/websocket/update-thingie.js, packages/fe/components/thingies/thingie.vue, packages/fe/components/thingies/touch-editor.vue, packages/fe/components/thingies/touch-thingie.vue, packages/fe/layouts/spaze.vue, packages/fe/modules/compost/components/compost-portal.vue, packages/fe/modules/pocket/components/pocket.vue, packages/fe/pages/_id.vue, packages/fe/store/collections.js
Button to delete thingies from the compost page. When using a touch device, an option will appear to delete thingies in the popup editor.
=> feat: delete thingie from compost

packages/be/modules/auth/rest/get-authenticate.js, packages/fe/components/auth.vue, packages/fe/pages/_id.vue, packages/fe/store/general.js
Add auth token to local storage for 3 hours automatic login.
=> feat: add auth token to local storage for 3 hours

packages/fe/components/pop-spz.vue
Disable get traces for new page creation
=> refactor: disable get traces

packages/fe/components/landing-site.vue, packages/fe/data/landing.json
updated tips for deleting thingies
=> feat: updated tips for deleting thingies

packages/fe/data/landing.json
updated tips with more descriptive instructions for deleting thingies
=> feat: updated tips

packages/be/modules/thingie/model/index.js, packages/fe/components/css-breakout-box.vue, packages/fe/components/prop-board.vue, packages/fe/components/thingies/image-thingie.vue, packages/fe/components/thingies/sound-thingie.vue, packages/fe/components/thingies/text-thingie.vue, packages/fe/components/thingies/thingie.vue, packages/fe/components/thingies/touch-editor.vue, packages/fe/components/thingies/touch-thingie.vue, packages/fe/data/thingie-editable-params.json, packages/fe/pages/_id.vue
Breakout box component added to desktop mode where css can be directly manipulated and saved in the data base per thingie. Also an opacity control has been added to all thingie types.
=> feat: css breakout controls

packages/fe/components/css-breakout-box.vue, packages/fe/pages/_id.vue
removing whitespace breaks some styles
=> fix: removing whitespace breaks some styles

packages/fe/pages/_id.vue
replace before psuedo element with child div
=> test: replace before psuedo element with child div

packages/fe/pages/_id.vue
remove opacity for screencap and readd on finish
=> feat: remove opacity for screencap and readd on finish

packages/be/crons/fuites/index.js, packages/be/crons/fuites/websocket/migrate-thingie.js, packages/be/crons/rules.json, packages/be/modules/page/model/index.js, packages/be/modules/page/rest/post-update-page.js, packages/be/modules/thingie/websocket/update-thingie.js, packages/be/scripts/pool-scraper.js, packages/fe/layouts/page.vue, packages/fe/modules/pocket/components/pocket.vue, packages/fe/nuxt.config.js, packages/fe/pages/_id.vue, packages/fe/plugins/sharpen-canvas.js, packages/fe/store/collections.js
- Added blur and sharpen to canvas rendered by 'html2canvas'. 
- Lowered quality on saved image data URL. 
- Moved background image outside of page element. The two are now siblings.
=> feat: background stain

packages/fe/pages/_id.vue
change page thingies to opacity 0.5 on screen cap
=> feat: change page thingies to opacity 0.5 on screen cap

packages/fe/pages/_id.vue
=> feat: opaque bg on screencap

packages/fe/pages/_id.vue
=> feat: half opacity on bg

packages/fe/pages/_id.vue
=> test: remove clone doc manipulation

packages/be/modules/print/rest/get-page-background.js, packages/be/modules/print/rest/post-update-background.js, packages/fe/pages/_id.vue, packages/fe/store/collections.js
Screencaps only layer if immediately set in the DOM background element.
=> test: screencap immediate update

packages/be/package.json, packages/fe/package.json
=> chore: version bump

packages/be/modules/print/rest/get-page-background.js, packages/fe/components/portal.vue, packages/fe/pages/_id.vue
reduce size on generated dataurl and add previews to portals
=> feat: reduce size on generated dataurl and add previews to portals

packages/be/scripts/pool-scraper.js, packages/be/static/pool-entries.txt
=> feat: update pool scraper

packages/be/liftoff.js
fix: clone deep import statement
=> fix: clone deep import statement

packages/music/package.json
fix: update launch command in music package
=> fix: update launch command in music package

packages/be/crons/cyanobot/index.js, packages/be/crons/fuites/index.js, packages/be/crons/goa/index.js, packages/be/crons/scavenger/index.js, packages/be/crons/scavenger/websocket/digest-compost-thingie.js, packages/be/crons/tunneler/index.js, packages/be/modules/utilities/index.js, packages/fe/pages/_id.vue, packages/interweave/pages/_id.vue, packages/music/pages/_id.vue
update crons to work with new mongo instance structure
=> feat: update cron instances

packages/interweave/components/thingies/sound-thingie.vue
test: interweave add audio src after cross origin attr
=> test: interweave add audio src after cross origin attr

packages/interweave/nuxt.config.js, packages/music/components/thingies/sound-thingie.vue, packages/music/nuxt.config.js
add package name to nuxt config backend url in packages
=> fix: add package name to nuxt config backend url in packages

packages/fe/layouts/page.vue, packages/fe/pages/_id.vue, packages/fe/store/general.js
toggle background shadow traces
=> feat: toggle background shadow traces

packages/fe/components/auth.vue, packages/fe/components/landing-site.vue, packages/fe/components/thingies/touch-thingie.vue, packages/fe/data/landing.json, packages/fe/pages/_id.vue
=> feat: bypass token

packages/fe/pages/_id.vue
=> fix: console log

packages/interweave/components/thingies/thingie.vue, packages/interweave/components/thingies/video-thingie.vue, packages/interweave/data/thingie-editable-params.json, packages/interweave/layouts/page.vue, packages/interweave/modules/pocket/components/single-file-uploader.vue, packages/interweave/store/general.js
video thingie component added to interweave package with video mimetype support added to uploader.
=> feat: video thingie + video mimetype support added to uploader

packages/interweave/components/thingies/video-thingie.vue, packages/interweave/components/touchmode-toolbar.vue, packages/interweave/layouts/page.vue, packages/interweave/modules/pocket/components/pocket.vue, packages/interweave/modules/pocket/components/single-file-uploader.vue, packages/interweave/modules/uploader/components/upload-input.vue, packages/interweave/store/general.js
Video muted without audio context, max upload size and video toggle for touch devices.
=> feat: video thingie updates

packages/be/crons/rules.json, packages/be/crons/tunneler/index.js
Add cron rules for the interweave tunneler.
=> feat: instance cron rules

packages/blinkrate/components/prop-board.vue, packages/blinkrate/store/collections.js, packages/fe/components/prop-board.vue, packages/fe/store/collections.js, packages/interweave/components/prop-board.vue
Create portal in fe and blinkrate, copied from interweave.
=> feat: create portal

packages/be/crons/scavenger/index.js, packages/be/modules/page/rest/post-create-page.js, packages/fe/components/thingies/thingie.vue, packages/fe/modules/pocket/components/pocket.vue, packages/fe/pages/_id.vue
✅fixed - Bug**: Thingies often get lost or stuck around the edges/corners of pages, and in the edges corners of the pocket which are out of sight
fix → Find out how some manage to get around the bounds or, just move them back into the page using the cleanup cron to edit their position in the database (see ‘Cleanup Cron’ below).
✅fixed - Bug: Drag n drop functionality often drops things in really unpredictable places, sometimes thingies jump to the top left of the page on drop
fix → Thingies should land at the position where they were dropped when releasing the mouse
=> feat: fixes queue

packages/music/components/info-panel.vue, packages/music/components/release-card.vue, packages/music/components/releases-panel.vue, packages/music/data/landing.json, packages/music/pages/index.vue
content for launch and release route query
=> feat: music tweaks

packages/fe/components/thingies/thingie.vue, packages/fe/components/thingies/touch-editor.vue, packages/fe/components/touchmode-toolbar.vue, packages/fe/layouts/page.vue, packages/fe/modules/pocket/components/pocket.vue, packages/fe/pages/_id.vue, packages/fe/store/general.js
=> feat: touchmode bug fixes

packages/fe/components/thingie/sound.vue
fix: calculate mouse distance from thingie with scene pan and zoom
=> fix: sound thingies

packages/fe/components/compost/portal.vue, packages/fe/components/portal.vue, packages/fe/nuxt.config.js, packages/fe/pages/[verse]/[page].vue, packages/fe/pages/index.vue, packages/fe/pages/info.vue, packages/fe/pages/multiverse.vue, packages/fe/stores/verse.js
Replace Nuxt Content module and queries with basic json file imports. Nuxt content is not loading in production so this might be a potential fix.
=> refactor: fetch async data

packages/fe/components/thingie/image.vue, packages/fe/components/thingie/text.vue, packages/fe/components/thingie/thingie.vue, packages/fe/composables/use-pageshot-bot.js, packages/fe/pages/[verse]/[page].vue
feat: image and text thingie load trigger screenshot
=> feat: image and text thingie load trigger screenshot

packages/be/modules/portal/rest/post-delete-portal.js, packages/be/modules/portal/websocket/update-portal.js, packages/fe/components/portal.vue, packages/fe/components/verse/delete-portal-alert.vue, packages/fe/components/verse/viewport.vue, packages/fe/layouts/default.vue, packages/fe/pages/[verse]/[page].vue, packages/fe/stores/general.js, packages/fe/stores/verse.js
Portals can be moved anywhere on a page. Portals that were created manually can be also be deleted. Tunneler portals can't be deleted.
=> feat: portal editing

packages/fe/composables/use-pageshot-bot.js, packages/fe/pages/[verse]/[page].vue
Update the pageshot bot composable to include a download to client option.
=> feat: download screenshot to client

packages/be/modules/auth/rest/authenticate-pocket.js, packages/be/modules/invite/rest/post-accept-invite.js, packages/be/modules/invite/rest/post-generate-invite.js, packages/be/modules/pocket/rest/check-token-exists.js, packages/be/modules/pocket/rest/post-add-token-verse.js, packages/be/modules/pocket/rest/post-create-pocket.js, packages/be/modules/verse/rest/post-create-verse.js, packages/fe/components/multiverse/create-verse-alert.vue, packages/fe/stores/pocket.js
Adds salting to token hashing.
=> feat: add salt secret to hashed token

package-lock.json, packages/be/crons/upload-migrator/index.js, packages/be/package.json
Adds AWS s3 storage package to interface with DigitalOcean Spaces. A script has been added to the crons folder which will loop through all uploads and prints on the server and copy them to the DigitalOcean Spaces bucket.
=> feat: upload and print migrator script in crons folder

packages/fe/components/portal.vue, packages/fe/components/verse/viewport.vue, packages/fe/pages/[verse]/[page].vue
Touch device support for working with portals and navigating through portals.
=> feat: portal touch support

packages/fe/components/portal.vue, packages/fe/components/verse/viewport.vue, packages/fe/pages/[verse]/[page].vue
=> feat: merge stable

packages/fe/components/caddy/mobile-font-editor.vue, packages/fe/components/caddy/mobile.vue, packages/fe/components/icon/mobile-bold.vue, packages/fe/components/icon/mobile-font-decrease.vue, packages/fe/components/icon/mobile-font-increase.vue, packages/fe/components/icon/mobile-italic.vue, packages/fe/components/icon/mobile-underline.vue, packages/fe/components/pocket/canvas.vue, packages/fe/components/svg/caddy-mobile-font-editor-background.vue, packages/fe/components/verse/text-editor.vue, packages/fe/components/verse/viewport.vue, packages/fe/nuxt.config.js, packages/fe/pages/[verse]/[page].vue
Mobile text editor + prevent native zoom in and canvas select
=> feat: mobile text editor

package-lock.json, packages/fe/components/verse/create-sound-thingie-alert.vue, packages/fe/modules/mixer/stores/use-mixer-store.js, packages/fe/package.json
Download thingie to wav and cut wav buffer to loop length.
=> feat: download thingie
